spring.application.name=app

server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3307/app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password = brayan15

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true

